dataset:
  name: libero
  transforms_1: (0.5)
  transforms_2: (0.5)
  load_saved: True
  save: True
  img_dir: ../LIBERO/libero/datasets/libero_90/
  bddl_dir: ../LIBERO/libero/libero/bddl_files/libero_90/
  train_test_split: 0.8
  img_size: 128
  batch_size: 512
  test_batch_size: 1000
  num_channels: 3
  num_concepts: 22
model:
  type: cb_vaegan
  latent_noise_dim: 256
  input_latent_dim: 64
  pre_concept_latent_dim: 256
  pre_concept_layers: 1
  has_concepts: True
  concepts:
      emb_size: 32
      concept_output: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
      concept_bins: [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
      concept_names: [
        'white_yellow_mug',
        'butter',
        'wine_bottle',
        'yellow_book',
        'ketchup',
        'tomato_sauce',
        'orange_juice',
        'porcelain_mug',
        'chefmate_8_frypan',
        'cream_cheese',
        'plate',
        'chocolate_pudding',
        'red_coffee_mug',
        'moka_pot',
        'basket',
        'milk',
        'white_bowl',
        'wooden_tray',
        'akita_black_bowl',
        'alphabet_soup',
        'black_book',
        'new_salad_dressing'
      ]
      types: ["bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin", "bin"]
      concept_latent: [64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64]
      concept_hidden: [124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124,124]
train_config:
  epochs: 60
  gen_lr: 0.0006
  dis_lr: 0.0002
  betas: (.5, .999)
  save_model: True
  use_cuda: True
  log_interval: 100
  plot_loss: True
evaluation:
  generation: True
  save_images: True
  save_results: True